outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/nccr/nccr/strainPrimer/data
dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/mkmherzog/hfd/scratch/assembly
samplesFile: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/hardt/mkmherzog/hfd/data/processed/samples.txt