
from pathlib import Path
samples = ['Z5951', 'Z5841']



OUTDIR = Path(config['outDir'])
DATADIR = Path(config['dataDir'])


rule catch:
    input: [DATADIR/f'{sample}/{sample}.scaffolds.min500.fasta.gz' for sample in samples]
    output: OUTDIR/'catch/output.fasta'
    params:
        scratch = 1000,
        mem = 8000,
        time = 235,
        qerrfile = OUTDIR/f'logs/catch.qerr',
        qoutfile = OUTDIR/f'logs/catch.qout'
    conda:
        "envs/catch.yaml"
    log:
        log = OUTDIR/f'logs/catch.log'
    shell:
        "design.py {input} -pl 150 -c 0.05 --identify -o {output} &> {log.log}"


rule blastdb:
    input: [DATADIR/f'{sample}/{sample}.scaffolds.min500.fasta.gz' for sample in samples]
    output: touch(OUTDIR/'blastDB.done')
    params:
        catFasta = OUTDIR/'all_strain.fasta',
        scratch = 1000,
        mem = 8000,
        time = 235,
        qerrfile = OUTDIR/f'logs/blastdb.qerr',
        qoutfile = OUTDIR/f'logs/blastdb.qout'
    conda:
        "envs/blast.yaml"
    log:
        log = OUTDIR/f'logs/catch.log'
    threads:
        8
    shell:
        "zcat {input} > {params.catFasta}; "
        "makeblastdb -in {params.catFasta} -title HFD -dbtype nucl"

#
rule blast:
    input: query = OUTDIR/'catch/output.fasta',
        db = OUTDIR/'all_strain.fasta',
        dbDone = OUTDIR/'blastDB.done'
    output: blastFile = OUTDIR/'blast/blast.out'
    params:
        scratch = 1000,
        mem = 8000,
        time = 235,
        qerrfile = OUTDIR/f'logs/blast.qerr',
        qoutfile = OUTDIR/f'logs/blast.qout'
    conda:
        "envs/blast.yaml"
    threads:
        8
    shell:
         'blastn -db {input.db} -out {output.blastFile} '
         '-query {input.query} -outfmt '
         '"6 qseqid sseqid pident length qstart qend sstart send evalue bitscore qseq sstrand" '
         '-num_threads 8'

rule sortProbes:
    input: OUTDIR/'blast/blast.out',
    output: touch(OUTDIR/'blast/sortProbes.done')
    params:
        out_dir = OUTDIR/'blast',
        scratch = 1000,
        mem = 8000,
        time = 235,
        qerrfile = OUTDIR/f'logs/sortProbes.qerr',
        qoutfile = OUTDIR/f'logs/sortProbes.qout'
    conda:
        "envs/blast.yaml"
    log:
        log=OUTDIR/f'logs/sortProbes.log'

    shell:
         'python sort_blast_by_strain.py {input} {params.out_dir} '
